# Generated by Django 4.0.4 on 2022-06-04 20:31

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_item_id_alter_post_id_alter_site_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.upload_to),
        ),
    ]
